#!/bin/bash
# 發佈興櫃篩選報告到 GitHub Pages (docs/ 子目錄)
# 用法:
#   ./scripts/publish.sh           只更新 docs/index.html
#   ./scripts/publish.sh --push    更新 + git commit + push

set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

DOCS="docs"
mkdir -p "$DOCS"

# 1. 確認 docs 內有報告
COUNT=$(find "$DOCS" -maxdepth 1 -name '20*.html' | wc -l | tr -d ' ')
if [ "$COUNT" = "0" ]; then
    echo "❌ docs/ 沒有報告檔，請先執行: python3 screener.py"
    exit 1
fi

# 2. 重產 index.html
python3 - <<'PYEOF'
from pathlib import Path
from datetime import datetime
import re

docs = Path("docs")
files = sorted(
    [p for p in docs.glob("*.html") if re.match(r"\d{4}-\d{2}-\d{2}\.html", p.name)],
    reverse=True,
)
items = "\n".join(
    f'  <li><a href="{p.name}"><span class="date">📊 {p.stem}</span>'
    f'<span class="arrow">→</span></a></li>'
    for p in files
)
gen = datetime.now().strftime("%Y-%m-%d %H:%M")

html = f"""<!DOCTYPE html>
<html lang="zh-Hant">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>興櫃股票篩選報告</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ font-family: -apple-system, "PingFang TC", "Microsoft JhengHei", sans-serif;
       background: #0f172a; color: #e2e8f0; padding: 2rem;
       max-width: 720px; margin: 0 auto; line-height: 1.6; }}
h1 {{ font-size: 1.6rem; color: #22d3ee; margin: 0; }}
.brand {{ display: flex; align-items: center; gap: 12px; margin-bottom: .3rem; }}
.logo {{ width: 40px; height: 40px; object-fit: contain; }}
.subtitle {{ color: #94a3b8; margin-bottom: 1.5rem; font-size: .9rem; }}
ul {{ list-style: none; }}
li {{ margin-bottom: .5rem; }}
li a {{ display: flex; justify-content: space-between; align-items: center;
        padding: .8rem 1rem; background: #1e293b; border-radius: 8px;
        border-left: 3px solid #22d3ee; color: #e2e8f0; text-decoration: none;
        transition: background .15s; }}
li a:hover {{ background: #273449; }}
.date {{ font-weight: 600; }}
.arrow {{ color: #22d3ee; }}
.note {{ margin-top: 1.5rem; padding: 1rem; background: rgba(245,158,11,.1);
         border-left: 3px solid #f59e0b; border-radius: 6px;
         color: #fbbf24; font-size: .85rem; }}
.modes {{ margin: 1rem 0; color: #94a3b8; font-size: .85rem; }}
.modes b {{ color: #22d3ee; }}
footer {{ margin-top: 2rem; color: #64748b; font-size: .8rem; }}
</style>
</head>
<body>
<div class="brand">
  <img src="logo.png" alt="logo" class="logo">
  <h1>興櫃股票篩選</h1>
</div>
<p class="subtitle">資料源：櫃買中心興櫃當日行情表 ｜ 最後更新：{gen}</p>

<div class="modes">
報告內含兩種模式：<b>悠哉選</b>（高價活躍股）/ <b>短線飆股</b>（強勢突破），
頁面內可即時切換並調整門檻。
</div>

<ul>
{items if items else "  <li>目前無報告</li>"}
</ul>

<div class="note">
⚠ 興櫃市場無漲跌停限制、流動性較低，篩選結果僅供研究參考，不構成投資建議。
</div>

<footer>Generated by <code>screener.py</code> ｜ Source: TPEx Open Data 11747</footer>
</body>
</html>
"""
Path("docs/index.html").write_text(html, encoding="utf-8")
print(f"✓ index.html 已產生 ({len(files)} 個報告)")
PYEOF

# 3. push 到 GitHub
if [ "$1" = "--push" ]; then
    if [ ! -d ".git" ]; then
        echo "❌ 尚未 git init, 請先執行: git init && git remote add origin <URL>"
        exit 1
    fi
    git add -A
    git commit -m "Update reports: $(date +%Y-%m-%d)" || echo "(無變更)"
    git push origin main
    echo "✓ 已推送至 GitHub Pages"
else
    echo ""
    echo "📁 docs/ 已更新 ($COUNT 個報告)"
    echo "推送：$0 --push"
fi
